var data=[
  {
    "Periodo": "2019-01",
    "Kennedy": 25,
    "Carvajal": 29,
    "Centro de Alto rendimiento": 15,
    "Usaquén": 15,
    "Puente Aranda": 18,
    "San Cristóbal": 13,
    "Tunal": 16,
    "Guaymaral": 14,
    "Las Ferias": 13,
    "MinAmbiente": 14,
    "Suba": 17,
    "Fontibon": 14
  },
  {
    "Periodo": "2019-02",
    "Kennedy": 35,
    "Carvajal": 49,
    "Centro de Alto rendimiento": 26,
    "Usaquén": 24,
    "Puente Aranda": 25,
    "San Cristóbal": 18,
    "Tunal": 25,
    "Guaymaral": 23,
    "Las Ferias": 20,
    "MinAmbiente": 21,
    "Suba": 26,
    "Fontibon": 22
  },
  {
    "Periodo": "2019-03",
    "Kennedy": 37,
    "Carvajal": 52,
    "Centro de Alto rendimiento": 28,
    "Usaquén": 27,
    "Puente Aranda": 27,
    "San Cristóbal": 21,
    "Tunal": 28,
    "Guaymaral": 25,
    "Las Ferias": 28,
    "MinAmbiente": 25,
    "Suba": 29,
    "Fontibon": 25
  },
  {
    "Periodo": "2019-04",
    "Kennedy": 28,
    "Carvajal": 38,
    "Centro de Alto rendimiento": 19,
    "Usaquén": 18,
    "Puente Aranda": 20,
    "San Cristóbal": 14,
    "Tunal": 20,
    "Guaymaral": 15,
    "Las Ferias": 19,
    "MinAmbiente": 18,
    "Suba": 18,
    "Fontibon": 24
  },
  {
    "Periodo": "2019-05",
    "Kennedy": 23,
    "Carvajal": 34,
    "Centro de Alto rendimiento": 13,
    "Usaquén": 12,
    "Puente Aranda": 18,
    "San Cristóbal": 9,
    "Tunal": 15,
    "Guaymaral": 10,
    "Las Ferias": 12,
    "MinAmbiente": 13,
    "Suba": 11,
    "Fontibon": 18
  },
  {
    "Periodo": "2019-06",
    "Kennedy": 16,
    "Carvajal": 30,
    "Centro de Alto rendimiento": 7,
    "Usaquén": 8,
    "Puente Aranda": 12,
    "San Cristóbal": "",
    "Tunal": 8,
    "Guaymaral": 7,
    "Las Ferias": 8,
    "MinAmbiente": 7,
    "Suba": 8,
    "Fontibon": 13
  },
  {
    "Periodo": "2019-07",
    "Kennedy": 18,
    "Carvajal": 30,
    "Centro de Alto rendimiento": 8,
    "Usaquén": 9,
    "Puente Aranda": 12,
    "San Cristóbal": 5,
    "Tunal": 8,
    "Guaymaral": 8,
    "Las Ferias": 8,
    "MinAmbiente": 7,
    "Suba": 10,
    "Fontibon": 14
  },
  {
    "Periodo": "2019-08",
    "Kennedy": 20,
    "Carvajal": 34,
    "Centro de Alto rendimiento": 10,
    "Usaquén": 10,
    "Puente Aranda": 0,
    "San Cristóbal": 0,
    "Tunal": 11,
    "Guaymaral": 12,
    "Las Ferias": 10,
    "MinAmbiente": 10,
    "Suba": 15,
    "Fontibon": 16
  },
  {
    "Periodo": "2019-09",
    "Kennedy": 24,
    "Carvajal": 34,
    "Centro de Alto rendimiento": 12,
    "Usaquén": 12,
    "Puente Aranda": 0,
    "San Cristóbal": 0,
    "Tunal": 11,
    "Guaymaral": 11,
    "Las Ferias": 8,
    "MinAmbiente": 11,
    "Suba": 14,
    "Fontibon": 18
  },
  {
    "Periodo": "2019-10",
    "Kennedy": 26,
    "Carvajal": 38,
    "Centro de Alto rendimiento": 14,
    "Usaquén": 10,
    "Puente Aranda": 0,
    "San Cristóbal": 0,
    "Tunal": 15,
    "Guaymaral": 11,
    "Las Ferias": 1,
    "MinAmbiente": 12,
    "Suba": 14,
    "Fontibon": 20
  },
  {
    "Periodo": "2019-11",
    "Kennedy": 26,
    "Carvajal": 33,
    "Centro de Alto rendimiento": 15,
    "Usaquén": 14,
    "Puente Aranda": 0,
    "San Cristóbal": 0,
    "Tunal": 17,
    "Guaymaral": 13,
    "Las Ferias": 14,
    "MinAmbiente": 14,
    "Suba": 16,
    "Fontibon": 19
  },
  {
    "Periodo": "2019-12",
    "Kennedy": 27,
    "Carvajal": 34,
    "Centro de Alto rendimiento": 13,
    "Usaquén": 12,
    "Puente Aranda": 15,
    "San Cristóbal": 8,
    "Tunal": 15,
    "Guaymaral": 14,
    "Las Ferias": 16,
    "MinAmbiente": 13,
    "Suba": 15,
    "Fontibon": 20
  }
]
